[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "check-yaml" }, { id = "end-of-file-fixer" }]

[[repos]]
repo = "local"
hooks = [
  { id = "ruff-check", name = "ruff check", language = "system", entry = "uv run ruff check", args = ["--fix"], types_or = ["python", "pyi"] },
  { id = "ruff-format", name = "ruff format", language = "system", entry = "uv run ruff format", types_or = ["python", "pyi"] },
]
